### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'current') when adding --turbo in Next.js

### ISSUE THREAD

**Issue by pjborowiecki** [resend/resend-node#258]
I have already raised this issue at Vercel's repo. Full description and a source code can be found [here](https://github.com/vercel/next.js/issues/57936), but thought I'll post it here as well. Not sure whether it's on Vercel's or your part, but I hope it gets fixed soon. Thanks a lot!

**Comment by t6adev** [comment]
In my case, an error message was `TypeError: Cannot read properties of undefined (reading 'create') ` in Next.js v14.0.1 with server action.
Not sure where the problem at.

**Comment by CarlosZiegler** [comment]
Same problem here:
`TypeError: Cannot read properties of undefined (reading 'current')
    at performWork (/Users/carlosziegler/my_projects/payrolles-web/.next/server/chunks/35a94_next_dist_compiled_react-dom_cjs_react-dom-server-legacy_node_development_03cc10.js:9559:57)
    at /Users/carlosziegler/my_projects/payrolles-web/.next/server/chunks/35a94_next_dist_compiled_react-dom_cjs_react-dom-server-legacy_node_development_03cc10.js:9884:28
    at scheduleWork (/Users/carlosziegler/my_projects/payrolles-web/.next/server/chunks/35a94_next_dist_compiled_react-dom_cjs_react-dom-server-legacy_node_development_03cc10.js:148:13)
    at startWork (/Users/carlosziegler/my_projects/payrolles-web/.next/server/chunks/35a94_next_dist_compiled_react-dom_cjs_react-dom-server-legacy_node_development_03cc10.js:9883:17)
    at renderToStringImpl (/Users/carlosziegler/my_projects/payrolles-web/.next/server/chunks/35a94_next_dist_compiled_react-dom_cjs_react-dom-server-legacy_node_development_03cc10.js:10005:13)
    at renderToString (/Users/carlosziegler/my_projects/payrolles-web/.next/server/chunks/35a94_next_dist_compiled_react-dom_cjs_react-dom-server-legacy_node_development_03cc10.js:10076:20)
    at /Users/carlosziegler/my_projects/payrolles-web/.next/server/chunks/node_modules__pnpm_99c02e._.js:8488:38
    at Generator.next (<anonymous>)
    at fulfilled (/Users/carlosziegler/my_projects/payrolles-web/.next/server/chunks/node_modules__pnpm_99c02e._.js:8416:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by collinversluis** [comment]
+1 I am having the same issue when compiling with turbo

**Comment by johanguse** [comment]
Same here! I spent a lot of time trying to send emails with React until I realized the problem wasn't in my code. Even though the issue on the Vercel repo was closed, I wanted to mention that it's still happening for me.

cc @bukinoshita

**Comment by collinversluis** [comment]
Via Krithika in an email to me from resend:

Could you please try adding resend to the serverComponentsExternalPacakge [inside your](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages) next.config and see if this resolves it? Our team made some updates for this.


IE:
`  experimental: {
    serverComponentsExternalPackages: ['resend']
  },`

![image](https://github.com/resend/resend-node/assets/69984704/970f9171-ef7d-41da-9ede-48a5eb52fa81)

@johanguse try this and see if it works for you

**Comment by WoetDev** [comment]
Also running into this error that's blocking all my builds with Next.js 14.2.3; wasn't sure if it's resend or react-email so added an issue here: https://github.com/resend/react-email/issues/1499

None of the workarounds are working for me, so I hope we can find a resolution soon!

**Comment by gabrielmfern** [comment]
As mentioned in https://github.com/resend/react-email/issues/1499, this was an issue with Next.js, and was fixed after v15 IIRC.
